In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [84]:
df=pd.read_csv('Heart_Disease_Prediction.csv')

In [85]:
df.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium Heart Disease  
0                        3         3      Presence  
1                        0         7       Absence  
2                        0         7      Presence  
3                        1         7       Absence  
4                        1         3       Absence

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
le=LabelEncoder()
for i in df['Heart Disease']:
    df['Heart Disease']=le.fit_transform(df['Heart Disease'])

In [88]:
df.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium  Heart Disease  
0                        3         3              1  
1                        0         7              0  
2                        0         7              1  
3                        1         7              0  
4                        1         3              0

In [89]:
df.columns

Index(['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease'],
      dtype='object')

In [90]:
X=df[['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium']]

In [91]:
X.head()

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium  
0                        3         3  
1                        0         7  
2                        0         7  
3                        1         7  
4                        1         3

In [92]:
y=df['Heart Disease']

In [93]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Heart Disease, dtype: int64

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [96]:
from sklearn.tree import DecisionTreeClassifier

In [97]:
tree=DecisionTreeClassifier(criterion='entropy')

In [98]:
tree

DecisionTreeClassifier(criterion='entropy')

In [99]:
tree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [100]:
y_pred=tree.predict(X_test)

In [101]:
y_pred[0:5]

array([1, 0, 1, 1, 0])

In [102]:
y_test[0:5]

1      0
102    0
147    1
186    1
180    0
Name: Heart Disease, dtype: int64

In [103]:
from sklearn import metrics

In [104]:
print('The accuracy of the model is ',metrics.accuracy_score(y_pred,y_test))

The accuracy of the model is  0.6851851851851852


# Logistic Rregression

In [105]:
from sklearn.linear_model import LogisticRegression

In [106]:
lo=LogisticRegression()

In [107]:
lo.fit(X_train,y_train)

/Users/fidaalibaig/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [108]:
y_pred1=lo.predict(X_test)

In [109]:
y_pred1[0:10]

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1])

In [110]:
y_test[0:10]

1      0
102    0
147    1
186    1
180    0
164    0
215    0
139    0
12     0
3      0
Name: Heart Disease, dtype: int64

In [111]:
from sklearn import metrics

In [112]:
print("The accuracy of the model is ",metrics.accuracy_score(y_pred1,y_test))

The accuracy of the model is  0.8518518518518519


# KNN

In [113]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
neigh=KNeighborsClassifier(n_neighbors=3)

In [115]:
neigh

KNeighborsClassifier(n_neighbors=3)

In [116]:
neigh.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [117]:
y_pred2=neigh.predict(X_test)

In [118]:
y_pred2[0:10]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [119]:
y_test[0:10]

1      0
102    0
147    1
186    1
180    0
164    0
215    0
139    0
12     0
3      0
Name: Heart Disease, dtype: int64

In [120]:
from sklearn import metrics

In [121]:
print("The accuracy of the matrix is ",metrics.accuracy_score(y_pred2,y_test))

The accuracy of the matrix is  0.6666666666666666


In [127]:
accuracy=[]
for i in range(1,10):
    neigh=KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train,y_train)
    y_pred3=neigh.predict(X_test)
    accuracy.append(metrics.accuracy_score(y_test,y_pred3))

In [129]:
print(accuracy)

[0.6481481481481481, 0.6851851851851852, 0.6666666666666666, 0.6666666666666666, 0.6851851851851852, 0.6481481481481481, 0.6851851851851852, 0.6851851851851852, 0.6851851851851852]


In [133]:
x=max(accuracy)

In [134]:
x

0.6851851851851852

In [136]:
count=1
for i in accuracy:
    if(i==x):
        break
    else:
        count+=1
print("The accuracy of the model is ",x,"for k=",count)

The accuracy of the model is  0.6851851851851852 for k= 2
