# importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# loading Dataset

In [2]:
df=pd.read_csv("cell_samples.csv")

In [3]:
df.head()

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [4]:
df.columns

Index(['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit', 'Class'],
      dtype='object')

# Data Preprocessing 

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
    df[i]=le.fit_transform(df[i])

In [17]:
feature_df = df[['Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize', 'BareNuc', 'BlandChrom', 'NormNucl', 'Mit']]
X = np.asarray(feature_df)
X[0:5]

array([[4, 0, 0, 0, 1, 0, 2, 0, 0],
       [4, 3, 3, 4, 6, 9, 2, 1, 0],
       [2, 0, 0, 0, 1, 1, 2, 0, 0],
       [5, 7, 7, 0, 2, 3, 2, 6, 0],
       [3, 0, 0, 2, 1, 0, 2, 0, 0]])

In [18]:
X[0:5]

array([[4, 0, 0, 0, 1, 0, 2, 0, 0],
       [4, 3, 3, 4, 6, 9, 2, 1, 0],
       [2, 0, 0, 0, 1, 1, 2, 0, 0],
       [5, 7, 7, 0, 2, 3, 2, 6, 0],
       [3, 0, 0, 2, 1, 0, 2, 0, 0]])

In [19]:
y=df['Class']

In [20]:
y[0:5]

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)

In [23]:
print("Training set:",X_train.shape)
print("Testing set ",y_test.shape)

Training set: (546, 9)
Testing set  (137,)


# Model Building

In [24]:
from sklearn import svm

In [25]:
clf=svm.SVC(kernel='rbf')

In [26]:
df = df[pd.to_numeric(df['BareNuc'], errors='coerce').notnull()]
df['BareNuc'] = df['BareNuc'].astype('int')
df.dtypes

ID             int64
Clump          int64
UnifSize       int64
UnifShape      int64
MargAdh        int64
SingEpiSize    int64
BareNuc        int64
BlandChrom     int64
NormNucl       int64
Mit            int64
Class          int64
dtype: object

In [27]:
clf.fit(X_train,y_train)

SVC()

In [28]:
yhat=clf.predict(X_test)

In [39]:
print('actual values \n', y_test[0:5])
print('predicted values\n', yhat[0:5])

actual values 
 693    0
669    1
545    0
106    1
185    0
Name: Class, dtype: int64
predicted values
 [0 1 0 1 0]


In [40]:
from sklearn import metrics

In [41]:
print("Accuracy of the model is ",metrics.accuracy_score(y_test,yhat))

Accuracy of the model is  0.9635036496350365
